include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = AirPodsGlyphPrefs

$(BUNDLE_NAME)_FILES = APGRootListController.m
$(BUNDLE_NAME)_FRAMEWORKS = UIKit MediaPlayer
$(BUNDLE_NAME)_PRIVATE_FRAMEWORKS = Preferences
$(BUNDLE_NAME)_INSTALL_PATH = /Library/PreferenceBundles
$(BUNDLE_NAME)_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/bundle.mk
